require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkCardsController do

  before do
    WorkCard.delete_all
  end

  after do
    WorkCard.delete_all
  end

  # This should return the minimal set of attributes required to create a valid
  # WorkCard. As you add validations to WorkCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "start_at" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all work_cards as @work_cards" do
      work_card = WorkCard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:work_cards).to_a.should eq([work_card])
    end
  end

  describe "GET show" do
    it "assigns the requested work_card as @work_card" do
      work_card = WorkCard.create! valid_attributes
      get :show, {:id => work_card.to_param}, valid_session
      assigns(:work_card).should eq(work_card)
    end
  end

  describe "GET new" do
    it "assigns a new work_card as @work_card" do
      get :new, {}, valid_session
      assigns(:work_card).should be_a_new(WorkCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested work_card as @work_card" do
      work_card = WorkCard.create! valid_attributes
      get :edit, {:id => work_card.to_param}, valid_session
      assigns(:work_card).should eq(work_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorkCard" do
        expect {
          post :create, {:work_card => valid_attributes}, valid_session
        }.to change(WorkCard, :count).by(1)
      end

      it "assigns a newly created work_card as @work_card" do
        post :create, {:work_card => valid_attributes}, valid_session
        assigns(:work_card).should be_a(WorkCard)
        assigns(:work_card).should be_persisted
      end

      it "redirects to the created work_card" do
        post :create, {:work_card => valid_attributes}, valid_session
        response.should redirect_to(WorkCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved work_card as @work_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkCard.any_instance.stub(:save).and_return(false)
        post :create, {:work_card => { "start_at" => "invalid value" }}, valid_session
        assigns(:work_card).should be_a_new(WorkCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkCard.any_instance.stub(:save).and_return(false)
        post :create, {:work_card => { "start_at" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested work_card" do
        work_card = WorkCard.create! valid_attributes
        # Assuming there are no other work_cards in the database, this
        # specifies that the WorkCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorkCard.any_instance.should_receive(:update).with({ "start_at" => "" })
        put :update, {:id => work_card.to_param, :work_card => { "start_at" => "" }}, valid_session
      end

      it "assigns the requested work_card as @work_card" do
        work_card = WorkCard.create! valid_attributes
        put :update, {:id => work_card.to_param, :work_card => valid_attributes}, valid_session
        assigns(:work_card).should eq(work_card)
      end

      it "redirects to the work_card" do
        work_card = WorkCard.create! valid_attributes
        put :update, {:id => work_card.to_param, :work_card => valid_attributes}, valid_session
        response.should redirect_to(work_card)
      end
    end

    describe "with invalid params" do
      it "assigns the work_card as @work_card" do
        work_card = WorkCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => work_card.to_param, :work_card => { "start_at" => "invalid value" }}, valid_session
        assigns(:work_card).should eq(work_card)
      end

      it "re-renders the 'edit' template" do
        work_card = WorkCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => work_card.to_param, :work_card => { "start_at" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested work_card" do
      work_card = WorkCard.create! valid_attributes
      expect {
        delete :destroy, {:id => work_card.to_param}, valid_session
      }.to change(WorkCard, :count).by(-1)
    end

    it "redirects to the work_cards list" do
      work_card = WorkCard.create! valid_attributes
      delete :destroy, {:id => work_card.to_param}, valid_session
      response.should redirect_to(work_cards_url)
    end
  end

end
